debug: false
logLevel: ERROR
defaultEntryPoints:
  - https
  - http
entryPoints:
  http:
    address: ':80'
    redirect:
      entryPoint: https
  https:
    address: ':443'
    tls: {}
retry: {}
docker:
  exposedByDefault: false
acme:
  email: greg@gregorywilliams.me
  storage: acme/certs.json
  entryPoint: https
  onHostRule: true
  httpChallenge:
    entryPoint: http
